import AppKit
import Foundation

@MainActor
final class ClipboardService {
    static let shared = ClipboardService()

    private var clearTimer: Timer?
    var clearDelay: TimeInterval = 30

    func copySecurely(_ string: String) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()

        pasteboard.setString(string, forType: .string)

        pasteboard.setData(
            Data(),
            forType: NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
        )
        pasteboard.setData(
            Data(),
            forType: NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
        )
        pasteboard.setData(
            Data(),
            forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
        )

        scheduleClipboardClear()
    }

    private func scheduleClipboardClear() {
        clearTimer?.invalidate()
        let changeCount = NSPasteboard.general.changeCount

        clearTimer = Timer.scheduledTimer(withTimeInterval: clearDelay, repeats: false) { _ in
            Task { @MainActor in
                let pasteboard = NSPasteboard.general
                if pasteboard.changeCount == changeCount {
                    pasteboard.clearContents()
                }
            }
        }
    }

    func clearImmediately() {
        clearTimer?.invalidate()
        NSPasteboard.general.clearContents()
    }
}
